build:
  image: docker
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  script:
    - docker build -t 1drop/akeneo:${AKENEO_VERSION} docker
    - docker push 1drop/akeneo:${AKENEO_VERSION}
  only:
    variables:
      - AKENEO_VERSION
