services:
  - docker:dind

build:
  image: docker
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  script:
    - docker build --build-arg AKENEO_VERSION=${AKENEO_VERSION} -t 1drop/akeneo:${AKENEO_VERSION} docker
    - docker push 1drop/akeneo:${AKENEO_VERSION}
  only:
    variables:
      - $AKENEO_VERSION
  tags:
    - docker
